### ISSUE TITLE
Allow preserving custom files e.g udev rules

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/suse-migration-services#100]
We have situations where we have lots of NICs in a server and to ensure the device names are identical on all servers the /etc/udev/rules.d/70-persistent-net.rules is adjusted.

In case we would "just" map the /etc/sysconfig/network/ things into the live system but not the udev rules, too - the ifcfg-<device> files would not match anymore to the "real" interfaces.

So now the question is "do we use the adjusted udev rules of the installed system also while running the Live system?"

**Comment by schaefi** [comment]
no the udev rules of the system to migrate and the live migration system are different. We don't inherit them from the system to migrate. The udev rules on the live migration system comes as they are provided in the target distribution which was used to build the live image. In our case this is what SLE15 provides.

>We have situations where we have lots of NICs in a server and to ensure the device names are >identical on all servers

You probably use net.ifnames=1 in combination with ```NAME=="", ENV{ID_NET_NAME_MAC}!="", NAME="$env{ID_NET_NAME_MAC}"``` in your udev rule

So yes this would be a problem for the current system.

I suggest we implement a service that allows copy of custom files which you can configure through the custom config file. Something like

```yaml
preserve:
  files:
     - /etc/udev/rules.d/70-persistent-net.rules 
```

Thoughts ?

**Comment by Martin-Weiss** [comment]
> 
> You probably use net.ifnames=1 in combination with `NAME=="", ENV{ID_NET_NAME_MAC}!="", NAME="$env{ID_NET_NAME_MAC}"` in your udev rule
> 

AFAIK the default is to have them based on MAC addresses on real hardware but we have several deployments where these were changed to PCI Bus ID:
i.e.:
`SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", KERNELS=="0000:82:00.0", NAME="eth0"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", KERNELS=="0000:82:00.1", NAME="eth1"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", KERNELS=="0000:82:00.2", NAME="eth2"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", KERNELS=="0000:82:00.3", NAME="eth3"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", KERNELS=="0000:04:00.0", NAME="eth4"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", KERNELS=="0000:04:00.1", NAME="eth5"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", KERNELS=="0000:01:00.0", NAME="eth6"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", KERNELS=="0000:01:00.1", NAME="eth7"`

> So yes this would be a problem for the current system.
> 

Ok - good that we found it!

> I suggest we implement a service that allows copy of custom files which you can configure through the custom config file. Something like
> 
> ```yaml
> preserve:
>   files:
>      - /etc/udev/rules.d/70-persistent-net.rules 
> ```
> 
> Thoughts ?

Can this then be "injected" before udev is executed in the live system and before the network service gets started? Then this would be great!

**Comment by schaefi** [comment]
We would copy files directly after the mount of the host system. After that we would re-trigger the udev events and the actions:

```
udevadm control --reload
udevadm trigger --type=subsystems --action=add
```

This should bring in the nic names as you expect it. But I'm guessing and the above should be tested prior the implementation. Can you or Tim do this ? I think that would be good as you have access to a system that runs in that way

Thanks

**Comment by Martin-Weiss** [comment]
> 
> 
> We would copy files directly after the mount of the host system. 

And at this point in time udev did not yet run to setup the NICs based on MAC addresses?

> After that we would re-trigger the udev events and the actions:
> 
> ```
> udevadm control --reload
> udevadm trigger --type=subsystems --action=add
> ```
> 
> This should bring in the nic names as you expect it. But I'm guessing and the above should be tested prior the implementation. Can you or Tim do this ? I think that would be good as you have access to a system that runs in that way
> 

Yes - I might be able to test this, here but I can not build this in IBS myself - so if you can provide me a build that includes this I can give it a try and verify.

**Comment by rjschwei** [comment]
OK, I get the problem, if we just pick up ifcfg-* files as we do currently and the interfaces are renumbered in the live system we will most likely have a problem and with a reasonably high likely hood not have access to a network that provides us with packages. 

I think supporting this as a configuration option is a reasonably straight forward approach that gets us out of guessing what we should do. I would choose a different name and make it specific to udev rules, i.e.

```
preserve:
  rules:
     - /etc/udev/rules.d/70-persistent-net.rules 
```
This way we can trigger udev only when `rules` are present and we can keep the more general `files` setting in our back pocket in case anything else comes up.

That said, please keep in mind that we are **NOT** intending to replace the existing "upgrade from ISO" path and some of these data center only cases will be out of scope.

**Comment by schaefi** [comment]
I think we are clear on expectations with this. Thanks for all the details. On a conversation with @Martin-Weiss we agreed this one to be the only mandatory implementation missing before the SES team can make use of the upgrade concept. Thus I set this as the only P1 in the current list. Once done I plan on a new release. Martin mentioned that @tserong might have already started to work on this one ? Tim if there is anything just let me know. If not we are happy to implement this part and you can expect a PR soon.

**Comment by schaefi** [comment]
ok I'm working on this now

**Comment by tserong** [comment]
Many thanks @schaefi. I was off work last week, and didn't have any code yet for this anyway, so there's no duplicated effort.
