### ISSUE TITLE
Question: Does the system support EFI based setups?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/suse-migration-services#106]
So far the majority of installations are based on legacy - but there are also some EFI based ones and now the question is if

a) the live system and the upgrade will work for EFI based setups, too
b) the activation will also support EFI based configurations

So is an EFI based setup supported, too?

**Comment by schaefi** [comment]
yes all this works the same on EFI based systems. We are using the grub loopback support and just add an additional loopback entry to a working bootloader configuration. This means a system that already uses EFI will find the entry in the config file and loopbacks the iso file from the uuid of the root device. The detection of the root device is independent of the boot method.
