### ISSUE TITLE
Use kexec instead of grub to boot into live migration system

### ISSUE THREAD

**Issue by schaefi** [SUSE/suse-migration-services#108]
Problem Description
================

The current way to boot into the live migration system and therefore start the migration is to reboot the machine and boot a pre-configured loopback grub menu entry. That menu entry is created through an activation script we provide as a package

The problem with this approach is that it does not work on all architectures. Only plain grub supported architectures can boot the migration system. Also in clouds like the Oracle cloud which boots machines through iSCSI via a network boot infrastructure and no direct requirement for a bootloader inside of the system will not be able to boot the live migration.

Alternative Solution
===============

Due to the bootloader restriction on the current architecture my idea was to get rid of the bootloader and directly boot the live migration system via ```kexec```. The activation script that usually creates a grub entry needs to be rewritten in a way that it extracts the kernel and initrd from the live migration iso image and just kexec's with the appropriate parameters. Instead of a reboot the user would need to call an ```activation_program``` we will provide with the activation package

That approach will also overcome the restriction of the bootloader to read from e.g encrypted root partitions.

**Comment by rjschwei** [comment]
I like the idea and agree that it is a good way to overcome existing limitations w.r.t. supporting architectures other than x86_64, and handling encrypted root volumes. The iSCSI boot case is still going to be very tricky, but very tricky is better than impossible.
