### ISSUE TITLE
The mounting of filesystems from the system to be migrated needs to be more selective to only attempt to mount filesystems relevant to the migration

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/suse-migration-services#110]
I have this in /etc/fstab:

`UUID=0b1b1a50-3fd8-45d3-9167-efc68926604d swap swap defaults 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 / btrfs defaults 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /boot/grub2/i386-pc btrfs subvol=@/boot/grub2/i386-pc 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /boot/grub2/x86_64-efi btrfs subvol=@/boot/grub2/x86_64-efi 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /home btrfs subvol=@/home 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /opt btrfs subvol=@/opt 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /srv btrfs subvol=@/srv 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /tmp btrfs subvol=@/tmp 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /usr/local btrfs subvol=@/usr/local 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/cache btrfs subvol=@/var/cache 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/crash btrfs subvol=@/var/crash 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/lib/libvirt/images btrfs subvol=@/var/lib/libvirt/images 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/lib/machines btrfs subvol=@/var/lib/machines 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/lib/mailman btrfs subvol=@/var/lib/mailman 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/lib/mariadb btrfs subvol=@/var/lib/mariadb 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/lib/mysql btrfs subvol=@/var/lib/mysql 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/lib/named btrfs subvol=@/var/lib/named 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/lib/pgsql btrfs subvol=@/var/lib/pgsql 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/log btrfs subvol=@/var/log 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/opt btrfs subvol=@/var/opt 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/spool btrfs subvol=@/var/spool 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /var/tmp btrfs subvol=@/var/tmp 0 0
UUID=df286cfc-3da3-4361-a2a6-155489aa2035 /.snapshots btrfs subvol=@/.snapshots 0 0
UUID=e7116ece-c7f3-4c3d-89e5-5ca2f4e30e35 /data                xfs        defaults              1 2
/data/isos/SLE-15-SP1-Installer-DVD-x86_64-GMC-DVD1.iso /srv/www/htdocs/sles15sp1 iso9660 ro,loop,auto       1 2
/data/isos/SUSE-Enterprise-Storage-6-DVD-x86_64-GMC-DVD1.iso /srv/www/htdocs/ses6 iso9660 ro,loop,auto       1 2
/data/isos/SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso /srv/www/htdocs/sles12sp3 iso9660 ro,loop,auto       1 2
/data/isos/SUSE-Enterprise-Storage-5-DVD-x86_64-GM-DVD1.iso /srv/www/htdocs/ses5 iso9660 ro,loop,auto       1 2
`
And this causes the mounting of the installed-system to fail during the live system boot with this error:
`-- Logs begin at Mon 2019-06-03 12:55:55 CEST, end at Mon 2019-06-03 13:11:37 CEST. --
Jun 03 12:56:49 localhost systemd[1]: Starting Mount System To Upgrade...
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Running mount system service
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Checking /system-root is mounted
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Mount system service: /system-root is mounted
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Checking /run/initramfs/isoscan is mounted
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Mount system service: /run/initramfs/isoscan is mounted
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Mount system service: mounting all entries
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Umount /system-root
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Umount /system-root
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Umount /system-root
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Umount /system-root
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Umount /system-root
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Umount /system-root
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Umount /system-root
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Umount /system-root
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Umount /system-root
Jun 03 12:56:52 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:52 | Umount /system-root
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Umount /system-root
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mount system in /system-root
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/boot/grub2/i386-pc
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/boot/grub2/x86_64-efi
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/home
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/opt
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/srv
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/tmp
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/usr/local
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/cache
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/crash
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/lib/libvirt/images
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/lib/machines
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/lib/mailman
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/lib/mariadb
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/lib/mysql
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/lib/named
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/lib/pgsql
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/log
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/opt
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/spool
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/var/tmp
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/.snapshots
Jun 03 12:56:53 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:53 | Mounting /system-root/data
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]: [INFO    ]: 12:56:54 | Mounting /system-root/srv/www/htdocs/sles15sp1
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]: [ERROR   ]: 12:56:54 | Mounting system for upgrade failed with mount: stderr: mount: /system-root/srv/www/htdocs/sles15sp1: failed to setup loop device for /data/isos/SLE-15-SP1-Installer-DVD-x86_64-GMC-DVD1.iso.
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]: , stdout: (no output on stdout)
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]: Traceback (most recent call last):
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]:   File "/usr/lib/python3.6/site-packages/suse_migration_services/units/mount_system.py", line 135, in mount_system
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]:     fstab_entry.device, mountpoint
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]:   File "/usr/lib/python3.6/site-packages/suse_migration_services/command.py", line 104, in run
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]:     command[0], error.decode(), output.decode()
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]: suse_migration_services.exceptions.DistMigrationCommandException: mount: stderr: mount: /system-root/srv/www/htdocs/sles15sp1: failed to setup loop device for /data/isos/SLE-15-SP1-Installer-DVD-x86_64-GMC-DVD1.iso.
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]: , stdout: (no output on stdout)
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]: During handling of the above exception, another exception occurred:
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]: Traceback (most recent call last):
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]:   File "/usr/bin/suse-migration-mount-system", line 11, in <module>
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]:     load_entry_point('suse-migration-services==0.5.30', 'console_scripts', 'suse-migration-mount-system')()
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]:   File "/usr/lib/python3.6/site-packages/suse_migration_services/units/mount_system.py", line 110, in main
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]:     mount_system(root_path, fstab)
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]:   File "/usr/lib/python3.6/site-packages/suse_migration_services/units/mount_system.py", line 149, in mount_system
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]:     'Mounting system for upgrade failed with {0}'.format(issue)
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]: suse_migration_services.exceptions.DistMigrationSystemMountException: Mounting system for upgrade failed with mount: stderr: mount: /system-root/srv/www/htdocs/sles15sp1: failed to setup loop device for /data/isos/SLE-15-SP1-Installer-DVD-x86_64-GMC-DVD1.iso.
Jun 03 12:56:54 localhost suse-migration-mount-system[1913]: , stdout: (no output on stdout)
Jun 03 12:56:54 localhost systemd[1]: suse-migration-mount-system.service: Main process exited, code=exited, status=1/FAILURE
Jun 03 12:56:54 localhost systemd[1]: Failed to start Mount System To Upgrade.
Jun 03 12:56:54 localhost systemd[1]: suse-migration-mount-system.service: Unit entered failed state.
Jun 03 12:56:54 localhost systemd[1]: suse-migration-mount-system.service: Failed with result 'exit-code'.
`

FYI  - even a "#" in front of the iso mount lines in fstab runs into the same error.

**Comment by tserong** [comment]
I'm not sure about the problem mounting ISOs yet (maybe we should just skip that type as well, as we do with swap?). As for commenting lines out, the fstab parser does not actually skip those. I have a fix for the latter, shall open a PR shortly.

**Comment by Martin-Weiss** [comment]
The connected ISOs could be installation sources / zypper repositories for SES / SLES - so just skipping them might not be the best way...

**Comment by schaefi** [comment]
> As for commenting lines out, the fstab parser does not actually skip those. I have a fix for the latter, shall open a PR shortly.

That would be great, yes please

**Comment by schaefi** [comment]
Regarding the iso entries in fstab we should find the reason why the loop mount does not work. This is strange

**Comment by tserong** [comment]
Found it... /etc/fstab specifies:

`/data/isos/SUSE-Enterprise-Storage-5-DVD-x86_64-GM-DVD1.iso /srv/www/htdocs/ses5 iso9660 ro,loop,auto 1 2`

Inside the mount_system unit (https://github.com/SUSE/suse-migration-services/blob/master/suse_migration_services/units/mount_system.py#L132-L136), this ends up being used like:

`mount -o ro,loop,auto /data/isos/SUSE-Enterprise-Storage-5-DVD-x86_64-GM-DVD1.iso /system-root/srv/www/htdocs/ses5 iso9660`

This doesn't work, because /data/isos/... is not a device accessible in the migration system, it's a file inside the root directory of the host. So we need to somehow check if the "device" part of an fstab line is actually a file on the host system, and in this case prepend /system-root/.

**Comment by rjschwei** [comment]
> The connected ISOs could be installation sources / zypper repositories for SES / SLES - so just skipping them might not be the best way...

If we want to support additional installation sources then we are probably better of supporting this as a configuration option. Chances would be that the additional installation source that is mounted/available on the current system is for that version of the distribution and will not work for wherever we are moving the system to. If there are kmps on the additional install source for example they will definitely not be used in the new system. I am not convinced we want to pick up everything that's in fstab.

**Comment by schaefi** [comment]
> I am not convinced we want to pick up everything that's in fstab.

That's in my opinion inevitable because fstab is the place that lists everything relevant for the system. So we have to go to all entries there and accept them as important for the system.

The way fstab is used here is in my opinion wrong. installation sources does not belong to fstab. an iso as zypper source should be added with the iso:// repo url to /etc/repos.d. Zypper takes care for the mounting and everything else.

As zypper is also used to drive the migration process this is the place where all repos should be managed. The reason that an iso needs to be mounted somewhere is not leading to the fact that they have to be listed in fstab.

So I'm sorry for me the way fstab is used here is a misuse and should not be done that way.

Thanks much for the "comment" patch. This was very well received.

@Martin-Weiss Please register the iso repos with zypper using the iso:// uri type. Please also delete them from fstab. If after that there is still a problem, let's open and discuss in a new issue

Thanks

**Comment by Martin-Weiss** [comment]
The server we are upgrading here is having an apache instance exporting mounted ISOs via HTTP.
So basically this is the AutoYaST and SMT server we are upgrading and we do not have an other source of installation sources than the local ones.
I can point the zypper repos with file:// to the local SMT data (which I have done anyway) - but we can not ensure that customers do not have loop mounted ISOS in their servers for other purposes..

**Comment by rjschwei** [comment]
Use the existing offline upgrade method by booting from the install media. Again, the migration system is not intended to replace the existing migration path.

Our initial goal was to handle running instances in a cloud environment, and we are willing to support the SES use case. That's it. the "general upgrade any system" implementation is out of scope for this project.

**Comment by Martin-Weiss** [comment]
In case of SES we have the admin node and on the admin node we have SMT and AutoYaST setups running in case the customer has "just SES" from SUSE. So when upgrading the SES admin node we have the problem with the loop mounted ISOS and local repositories in case the SMT is installed, there.
If we take this out of scope - we need to add a migration of SMT/AutoYaST/Repos to a further server before upgrading the admin node and that also would require the customer to get an extra SLES server.

**Comment by rjschwei** [comment]
There is no SMT on SLES 15 and higher, so the user has to handle the SMT-> RMT transition per documentation. No information from any of the applications, SMT, AutoYast, SES itself is needed to migrate the OS. As stated elsewhere for the migration we only need the mount points that are part of the system proper as defined by FHS. Your point is valid in so far that the sftab file my be "polluted" we stuff we do not care about and don't want to handle during migration. Therefore the code should probably be more picky about which entries from fstab we process. Meaning we should only attempt to mount things that follow the definitions that would apply to a filesystem that may be part of the "system proper", meaning we look for "/dev", "UUID", "LABEL", "ip-address:PATH", "hostname:PATH", "PARTUUID", and "PARTLABEL"

**Comment by schaefi** [comment]
Sorry but I have several concerns about this topic. The contents of fstab are in my opinion just wrong. I don't see any reason why we should try to be clever and implement that guessing code. We can only loose.

@Martin-Weiss what you have said about HTTP repos is something I don't understand at all. Your fstab doesn't list any remote sources:

```
UUID=e7116ece-c7f3-4c3d-89e5-5ca2f4e30e35 /data                xfs        defaults              1 2
```

There will be no problem with this and it seems to belong to the system, an extra /data, no problem, our code will just mount it below ```/system-root/data```

Next there are

```
/data/isos/SLE-15-SP1-Installer-DVD-x86_64-GMC-DVD1.iso /srv/www/htdocs/sles15sp1 iso9660 ro,loop,auto       1 2
/data/isos/SUSE-Enterprise-Storage-6-DVD-x86_64-GMC-DVD1.iso /srv/www/htdocs/ses6 iso9660 ro,loop,auto       1 2
/data/isos/SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso /srv/www/htdocs/sles12sp3 iso9660 ro,loop,auto       1 2
/data/isos/SUSE-Enterprise-Storage-5-DVD-x86_64-GM-DVD1.iso /srv/www/htdocs/ses5 iso9660 ro,loop,auto       1 2
```

Our code fails because /data/isos/... is not a device accessible in the migration system, it's a file inside the root directory of the host. So the location those files could be accessed would be in ```/system-root/data/isos/...```. Thus the real problem here is the self reference of a local path.

We have now two opportunities:

1. Ignore self root references and just skip this mount. This can be done in our code with a simple
    one liner path checking if the source dev exists. But usually all entries in fstab matters to the system.
    Your concept violates this but I would be willing to implement that extra check in our code

2. Add a fallback lookup for local dev nodes to also look below /system-root
    This can be done but I wouldn't be too enthusiastic about it

Apart from that I still think your iso loop mounts doesn't belong to the fstab. Your /data mount belongs there but the individual iso sources do not belong there. From my perspective you should delete any
loop entry from the fstab and instead register the local isos as follows:

```
zypper ar iso:/?iso=/data/isos/SUSE-Enterprise-Storage-5-DVD-x86_64-GM-DVD1.iso ses5
...
```

I don't understand why you need to mount DVDs to /srv/www/htdocs. From my understanding SUSE DVDs can only be used with a package manager and that's zypper. So that's the place to register it.
Maybe I misunderstood the concept though. If you are running a local instance serving SUSE DVDs then fstab is even more the wrong place. All that should be done by a local mirror e.g SMT/RMT or you write a simple systemd unit file that does this mounting for you at boot time but not fstab

@rjschwei Thanks for your effort in trying to be clever on reading the fstab but I'm sorry I don't think this is the right way to go. If the concept on the SES side can't be changed for whatever reason I'm willing to implement what I suggested in 1)

Thanks

**Comment by Martin-Weiss** [comment]
It seems I have to explain a bit more why these ISO mounts are in the fstab.

In SES deployments where the customer does not have anything else from SUSE we have to use the SES Admin Server also as RMT / SMT Server AND as Installation Repository Server and hosting the AutoYaST sources for installation of the other SES servers.

The best practice for this is to put the ISOs on this server and loop mount them to /srv/www/htdocs/... so that the other servers can boot via installer-iso and use install= / autoyast= for retrieving the installation sources from the loop mounted ISOs on the SES Admin server.

When upgrading the SES servers (not the admin) this is not a problem - but for upgrading the admin server itself - we need the installation sources available in zypper and we need to configure zypper to use the local provided repositories (as no other source is available).

So if the ISOs are loop mounted to /srv/www/htdocs... we use zypper with file:///srv/www/htdocs...

I am not sure if customers might also have other ISOs mounted locally via loopback and if these are required during the upgrade process.

But yes - as a workaround we can ignore the ISOs in /etc/fstab and we can adjust zypper to use zypper ar iso:/?iso=/data/isos/SUSE-Enterprise-Storage-5-DVD-x86_64-GM-DVD1.iso ses5 ! I will try to follow this approach in the next tests.

**Comment by rjschwei** [comment]
It sounds like there is confusion around upgrade of the application (SES) and the OS (SLES). The migration system only upgrades the underlying distribution, no packages from any product iso SES 5,6 or any number are going to be needed to upgrade the distribution.

**Comment by tserong** [comment]
`zypper migration` or `zypper dup` will update all installed products/packages, so if you've got SES5 installed, the upgrade does upgrade the system to SES6, in addition to upgrading SLE 12 SP3 to SLE 15 SP1. If wouldn't work if it only upgraded SLE and not SES (or whatever other products are installed)
