### ISSUE TITLE
Auto detect baseproduct to migrate

### ISSUE THREAD

**Issue by jesusbv** [SUSE/suse-migration-services#129]
When running the distribution migration system in a SLES SAP instance, if there is not custom file pointing to the right migration product, by default it will try to migrate to SLES 15 when it should be SLES SAP 15.

One option is to detect the baseproduct of the instance and migrate it to $VERSION.

**Comment by schaefi** [comment]
The auto detection is imho not complete since the merged code was only the needed product implementation refactoring

**Comment by jesusbv** [comment]
Yes, it is the refactoring. We decided to separate the process into steps where first one was refactor the current code, then auto detect the target product IIRC.
