### ISSUE TITLE
How to track progress

### ISSUE THREAD

**Issue by schaefi** [SUSE/suse-migration-services#13]
If the migration system gets booted a process of several depending services starts. If all goes well the system reboots and the migration is done. However if something fails the system cleans up and stays in this failed state ready for debugging.

* Assuming we are in a cloud and even if we have started sshd we won't be able to login because
  no boot init setup is currently setup in the migration iso image to register the system in the cloud.
  Thus at this point we don't know about the state or the error and can't access the instance

* Another scenario, if the zypper process takes long to migrate the system it would be good to be able
  to track the progress, meaning to get informed that something is happening and we are not in a failed
  state.

So this opens a bunch of design questions:

1. I think the migrate service should write a log file from the output of zypper migration such that
    we could ```tail -f``` it and see what's going on. It would also be possible to run this as a dialog based
    systemd service displaying the information on the primary console

2. If there would be a generic setup in cloud-init to register the instance such that ssh with a key would
    work we should consider to add that setup to the image build. I know it would be possible for GCE and
    EC2 as both clouds are supported by cloud-init but at least Azure has its own concept with the azure
    agent and I don't know if all of them can be combined in one image

3. In any case we should write the migration status on the console e.g the /etc/issue trick we used in the
    Azure Large Instance project such that we can fetch the console output through the cloud API and at
    least see the status

I'm open for crazy ideas, thoughts, flames :)

Thanks

**Comment by jesusbv** [comment]
>     1. I think the migrate service should write a log file from the output of zypper migration such that
>        we could `tail -f` it and see what's going on. It would also be possible to run this as a dialog based
>        systemd service displaying the information on the primary console
I agree. We could forward the log entries to journal and combine tail -f with journalctl

>     2. If there would be a generic setup in cloud-init to register the instance such that ssh with a key would
>        work we should consider to add that setup to the image build. I know it would be possible for GCE and
>        EC2 as both clouds are supported by cloud-init but at least Azure has its own concept with the azure
>        agent and I don't know if all of them can be combined in one image
It would be nice if it's possible to do it with cloud-init setup, I'm not sure if cloud-init is enabled for SUSE in Azure  (at least not in the [list](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-machines/linux/using-cloud-init.md#cloud-init-overview)) 
>     3. In any case we should write the migration status on the console e.g the /etc/issue trick we used in the
>        Azure Large Instance project such that we can fetch the console output through the cloud API and at
>        least see the status
Again, agree.

**Comment by rjschwei** [comment]
I do not like the idea of putting cloud-init into the migration. 

+ cloud-init is a rather large hammer to get 1 well defined value. 
+ the ssh key is already on the system that is being migrated. The user had to ssh in to install the migration package. 
+ the problem goes deeper. There is no guarantee that the framework has an ssh key or that the key known to the framework is actually being used. I can, relatively easily customize my instance that I am going to upgrade to not use a key that is known to the metadata server.

I agree that we need to give the user some way to help themselves should the migration fail. But for this I think we need to be more explicit in describing the failure modes and then making an assessment on the impact and what we think should happen. 

Prepare service:
   + we assume the copy of /etc/SUSEConnect works, we should probably not make that assumption and check the return value and exit on error.
   + if the bind mount fails we complain
   At this point nothing has happened to the system to be migrated. Thus leaving a log entry, maybe in /var/log/migration-service.log, on the disk of the system that is being migrated should be sufficient. We exit the migration system and fall back to the system that was to be migrated

Network setup service:
    + we assume the copy of /etc/resolve.conf works, we should probably not make that assumption and check the return value and exit on error.
    + we are missing /etc/hosts in the setup. We cannot assume that the repo server is DNS resolvable, we know in the Public Cloud they are not and /etc/hosts is needed in the migration system
    + if the bind mount fails we complain
    As with the prepare service nothing has happened to the system to be migrated. Thus we should behave in the same way as suggested with the prepare service.

Mounting:
    As with the previous services nothing has happened to the system to be migrated. Thus we should behave in the same way as suggested with the prepare service.

Unmounting:
    If we get here the system was migrated, ignore errors, kexec should force all mounts to be dropped

GRUB setup:
    + We need to separate the failure cases, i.e. 2 try blocks. If any of the mount commands fail we are in the same situation as the previously described services, i.e. leave a log entry and get back to the system to be migrated.
    + If grub2-mkconfig fails we potentially have modified the system to be migrated. I think we should make a backup copy of the grub config file and if grub2-mkconfig fails put the backup into place, then behave as previously described.

Migration (this was of course the trigger for the discussion):
    + We cannot determine the failure mode, I think. The failure mode could be an error in downloading the packages, in which case no harm is done and we could just leave. But since we don't know we cannot do that. I think if a failure occurs during migration we have to assume the worst case scenario, i.e. the system to be migrated is in an inconsistent state. In this case we have to figure out how to let the user login somehow, but see ssh problem above.
    + If we can determine where in the migration process the failure occurs we could potentially take different actions based on the failure modes.

Reboot:
    + If reboot fails the only option a user in the cloud has it to stop the instance, mount the disk to a running instance and look at the log. This is why writing the log to the system to be migrated is important. I suggest we write to a separate log, /var/log/migration-service.log

**Comment by rjschwei** [comment]
Getting the ssh key?

IMHO we should make the user point us to the ssh key they want to have in place in case something goes wrong, i.e.

zypper migration --major-distro-upgrade --emergency-ssh-key PATH_TO_AUTHORIZED_KEYS_FILE

then we can copy this file into the chroot from where we are running the migration and if something goes wrong the user can login with their ssh key.

Advantage of this approach:
- In the public cloud we do not have to go fishing on the metadata server for ssh key information which may or may not be useful to begin with
- This works the same in the Public Cloud as it would in the data center

**Comment by rjschwei** [comment]
Adding @thkukuk to the discussion for additional insight.

**Comment by rjschwei** [comment]
As far as writing to the console is concerned. Yes we should write to the console, but we cannot necessarily depend on being able to get the information from the Public Cloud framework. While the frameworks we support today have APIs to get the info there is no guarantee that other frameworks will also provide such a feature. Thus we need a permanent record on disk of the system that is being migrated. The "mount disk to running instance" will always work.

**Comment by schaefi** [comment]
> write to a separate log, /var/log/migration-service.log

I agree to that, we should have this log such that an external mount of the storage has a way to access it

> Yes we should write to the console...

Yes we should do that, even if there is no api or other access to the console it's good to write status there as it does not harm

> Regarding ssh

I'm still spinning my head around this. Thanks for the  feedback. It seems we don't want cloud-init and talking to metadata servers, which I'm ok with as I also see many ways to circumvent it

**Comment by schaefi** [comment]
Splitted the information from here into single issues with a more specific scope.
Also added the discussion points we talked about here in the small group in NUE
