### ISSUE TITLE
Rollback broken when registered to RMT because of repo refresh

### ISSUE THREAD

**Issue by ikapelyukhin** [SUSE/suse-migration-services#133]
If the migration fails, `zypper migration` tries to roll it back. It calls `SUSEConnect --rollback`, which in turn calls `zypper --no-remote --no-refresh --xmlout --non-interactive products -i` [[1]].

However, for whatever reason even when `--no-remote`, `--no-refresh` and `-i` flags are present, zypper still tries to refresh the repos.

At this point, all the products that were on the host system were de-registered from the registration server and some products in the migration path were registered instead.

So basically during rollback zypper tries to refresh the deactivated repos. Refreshing works when registered to SMT (because of it's authorization model) and when registered to SCC (because repo URLs still have valid auth tokens), but that doesn't work with PubCloud RMT.

Because of this `SUSEConnect --rollback` fails with:

```
Starting to sync system product activations to the server. This can take some time...
command 'zypper --no-remote --no-refresh --xmlout --non-interactive products -i' failed
Error: zypper returned (106) with '<?xml version='1.0'?>
<stream>
<message type="error">Error building the cache:
[repo|https://repo.path/] Valid metadata not found at specified URL
</message>
...
```

CC @rjschwei for interest.

[1]: https://github.com/SUSE/connect/blob/71e280d48d0d939a45dc8bf08cf7842138d0f36a/lib/suse/connect/zypper.rb#L52

**Comment by ikapelyukhin** [comment]
I have found that it's possible to prevent zypper from refreshing the repos with the addition of `--disable-repositories` flag. (`zypper --no-remote --no-refresh --disable-repositories products -i`)

@mlandres, @bzeller is that expected behavior? Aren't just `--no-remote`, `--no-refresh` and  `-i` flag for `products` command enough, does it have to be `--no-remote --no-refresh --disable-repositories products -i`?

**Comment by bzeller** [comment]
No it is not, if I try that locally with my system zypper it does not try to refresh repositories:
```
 ~  sudo zypper --no-remote --no-refresh --xmlout --non-interactive products -i                     
<?xml version='1.0'?>
<stream>
<message type="info">Ignoring repository &apos;openSUSE-Leap-15.1-Debug&apos; because of &apos;no-remote&apos; option.</message>
<message type="info">Ignoring repository &apos;openSUSE-Leap-15.1-Debug-Non-Oss&apos; because of &apos;no-remote&apos; option.</message>
<message type="info">Ignoring repository &apos;openSUSE-Leap-15.1-Update-Debug&apos; because of &apos;no-remote&apos; option.</message>
<message type="info">Ignoring repository &apos;openSUSE-Leap-15.1-Update-Debug-Non-Oss&apos; because of &apos;no-remote&apos; option.</message>
<message type="info">Ignoring repository &apos;openSUSE-Leap-15.1-Non-Oss&apos; because of &apos;no-remote&apos; option.</message>
<message type="info">Ignoring repository &apos;openSUSE-Leap-15.1-Oss&apos; because of &apos;no-remote&apos; option.</message>
<message type="info">Ignoring repository &apos;openSUSE-Leap-15.1-Oss-source&apos; because of &apos;no-remote&apos; option.</message>
<message type="info">Ignoring repository &apos;openSUSE-Leap-15.1-Source&apos; because of &apos;no-remote&apos; option.</message>
<message type="info">Ignoring repository &apos;openSUSE-Leap-15.1-Source-Non-Oss&apos; because of &apos;no-remote&apos; option.</message>
<message type="info">Ignoring repository &apos;openSUSE-Leap-15.1-Update&apos; because of &apos;no-remote&apos; option.</message>
<message type="info">Ignoring repository &apos;openSUSE-Leap-15.1-Update-Non-Oss&apos; because of &apos;no-remote&apos; option.</message>
<message type="info">Loading repository data...</message>
<message type="warning">No repositories defined. Operating only with the installed resolvables. Nothing can be installed.</message>
<message type="info">Reading installed packages...</message>
<product-list>
<product name="openSUSE" version="15.1" release="1" epoch="0" arch="x86_64" vendor="openSUSE" summary="openSUSE Leap 15.1" repo="@System" productline="Leap" registerrelease="" shortname="openSUSE Leap" flavor="ftp" isbase="true" installed="true"><endoflife time_t="1606694400" text="2020-11-30T01:00:00+01"/><registerflavor/><description>openSUSE Leap 15.1</description></product>
</product-list>
</stream>
```

**Comment by ikapelyukhin** [comment]
@bzeller oh, OK. In the PubCloud we use a URLResolver plugin, after some additional testing it seems that the presence of the plugin is causing this issue.

Could you please see if you can reproduct this like so:

1. Create `/usr/lib/zypp/plugins/urlresolver/test`:
```
#!/usr/bin/python2

import os
import sys
import time
from zypp_plugin import Plugin

class TestPlugin(Plugin):
  def RESOLVEURL(self, headers, body):
      self.answer({}, "http://example.org")

plugin = TestPlugin()
plugin.main()
```
2. Add the repo that uses this plugin: `zypper ar plugin:/test test`;
3. Run `zypper --no-remote --no-refresh --xmlout --non-interactive products -i`.

For me it exits with status code 106 and the following error in XML output:
```
<message type="error">Some of the repositories have not been refreshed because of an error.</message>
```

**Comment by mlandres** [comment]
If you use `--disable-repositories` there should be no need for `--no-remote --no-refresh`.

Maybe zypper should classify plugin:// as (probably) remote because Zypper can't  evaluate the plugin url.

**Comment by ikapelyukhin** [comment]
> If you use `--disable-repositories` there should be no need for `--no-remote --no-refresh`.
> 
> Maybe zypper should classify plugin:// as (probably) remote because Zypper can't evaluate the plugin url.

Well, I suppose URLResolver plugin might return `file://` URLs, so I guess it depends on each individual resolution result.

Would you recommend using `--disable-repositories` instead? I can fix the flags in SUSEConnect, would that have any other side effects?

**Comment by mlandres** [comment]
Note: `--no-refresh` just avoids an auto-refresh of metadata (you willingly use the local metadata as they are). If there are no local metadata at all, a refresh is forced.

**Comment by mlandres** [comment]
`--disable-repositories` is fine if you query for installed `-i` only.

**Comment by ikapelyukhin** [comment]
> `--disable-repositories` is fine if you query for installed `-i` only.

SUSEConnect is using the command to determine which products are already installed on the system, there should be no need to refresh the repos. Great, thanks for the confirmation.

**Comment by ikapelyukhin** [comment]
@schaefi @jesusbv I've opened a PR with a fix in SUSEConnect, but expect rollback to stay broken until it's released, which probably will take a while.

**Comment by schaefi** [comment]
@ikapelyukhin do you know about the release state ? Can this one be closed ?

Thanks

**Comment by ikapelyukhin** [comment]
@schaefi yep, SUSECoonect v0.3.20 was already released.
Consider adding `Requires: SUSEConnect >= 0.3.20` to the migration package.

**Comment by schaefi** [comment]
Thanks, I think as the zypper-migration-plugin ruby code is the caller of SUSEConnect, this package should probably take the Requires statement.

@jesusbv can you take a look at this, low prio though because if it's released the latest version is taken by the image build anyway

Thanks
