### ISSUE TITLE
Grub does not find ISO with more complex disk layout (separate /boot partition and LVM for root)

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/suse-migration-services#134]
We have an md0 for /boot and an md1 with lvm for the root filesystem.

/dev/md0 mounted to /boot with ext3
/dev/system/root (in LVM on md1) mounted to / with btrfs

In this scenario we get this error:
![grafik](https://user-images.githubusercontent.com/13362573/64978943-ee968480-d8b6-11e9-9c4e-eb81f932445b.png)

I am not sure if/how often we might see such a problem but maybe this can be fixed some day.

**Comment by schaefi** [comment]
Hmm, I guess our simple root_device setup might be wrong in this case. Before you rebooted can you please share the grub config file:

```/boot/grub2/grub.cfg```

Thanks.

Also the kexec based run_contained approach as documented here:

* https://documentation.suse.com/suse-distribution-migration-system/1.0/single-html/distribution-migration-system/#_run_the_migration

Could be an alternative ?

**Comment by schaefi** [comment]
@Martin-Weiss Is this still of interest ? If so could you provide the details I asked for ? Thanks

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss Is this still of interest ? If so could you provide the details I asked for ? Thanks

@schaefi - yes - AFAIK this problem still exists but unfortunately I do not have access to the original system anymore so can not provide the original grub.cfg. Probably we have to wait until I have the chance to reproduce during the next upgrade.

**Comment by schaefi** [comment]
ok in this case I'm going to close this one and we take a look at it once there is an opportunity to access all data for debugging. Thanks
