### ISSUE TITLE
Rename migration package

### ISSUE THREAD

**Issue by schaefi** [SUSE/suse-migration-services#147]
The package name of the migration from sles12 to sles15 is named ```SLES12-SP4-SLES15-Migration```. It was done that way because the original intend was to migrate sle12-sp4 to sle15 in the public cloud and nothing else

However the scope of the project is larger now. The storage team uses our concept and builds their own migration package and name.

Alex also said: you might want to also think about a different name of the package. SLES12-SP4-SLES15-Migration actually offers (will soon offer) migrations from SLES 12 SP3, SP4 and SP5 to SLES 15, but judging from the name one might think this is only available for SLES 12 SP4.

So we should rename the migration package to

a) include the target: PublicCloud such that we can differentiate our own offering from other teams, e.g storage
b) simplify such that the service pack name is of no relevance because the migration works for all service packs the repository server offers an upgrade path for.

My suggestion is:

* SLES12-SLES15-PubCloud-Migration

I'm open for other names, ideas

**Comment by schaefi** [comment]
We also have to clarify the correct obsoletes and provides setup to avoid mistakes.
@aosthof or @rjschwei if you know exactly how to do this right it would be great to get your feedback

I usually avoid package renames because it was such a nightmare :)

**Comment by schaefi** [comment]
Actually I should be more clear in my writing. So the image build in obs is named ```SLES12-SP4-SLES15-Migration``` This can be easily changed, because that name is never exposed to customers.

That image build is packaged as a package named ```SLES15-Migration```. We release that package to the customer in the SLE12 public cloud module. So that name is already generic.
It's imho not needed to have sle12 in this package name because it's released in the sle12 public cloud module which makes it obvious that ```SLES15-Migration``` performs a sles15 migration

I think what is missing is the scope. So maybe we change the name to:

* SLES15-PubCloud-Migration

Again I'm open for the name game :)

**Comment by schaefi** [comment]
As our package is only released in the sle12 public cloud module we can of course also argument that no scope information is needed in the package name because what comes from the public cloud module must be for public clouds.

In this case we can leave everything as it is right now :)

Feedback welcome

**Comment by aosthof** [comment]
Given the above info I'm fine with keeping it as `SLES15-Migration`.

**Comment by rjschwei** [comment]
We've not really had any issues w.r.t. confusion or collision I think the name is OK.

**Comment by schaefi** [comment]
> We've not really had any issues w.r.t. confusion or collision I think the name is OK.

ok makes sense to me so the name of the rpm package stays as it is. The image build building that package has been moved to: Devel:PubCloud:CrossCloud:SLE15-SP1/SLES15-SP1-Migration and follows the conventions we have recently setup there.

The image description itself is now also part of the suse-migration-services git repo. Image releases gets auto taged and the image rpm version is now the same as the suse-migration-services package. That brings everything into a manageable concept.

Thanks
