### ISSUE TITLE
OS mounting fails for external references

### ISSUE THREAD

**Issue by schaefi** [SUSE/suse-migration-services#165]
Recently we had a problem with a customer where the migration fails in the mount service.
The mount service searches the disks for an OS reads the fstab and mounts everything in the fstab under /system-root. This assumes the fstab contains only OS relevant entries. However on e.g HANA systems external storage references are mounted into the system as well. Inside of the migration live image those references are not available and mounting of those fails. In addition those external data is not relevant for the OS upgrade.

We should make the system mount unit more robust in a way that it only takes mountpoints into account that matches the disk which holds the fstab file.

Current workaround for customers is:

* cp etc/fstab away
* modify /etc/fstab to contain only OS entries
* reboot and upgrade
* move fstab back once the migrated system is up again
* mount -a

This process worked in the session with the customer and is ok as a workaround but the migration system can do better :)

**Comment by rjschwei** [comment]
Agreed. As a side note, in the cloud extra "disks" should always have the "nofail" option set, which would have possibly prevented DMS from failure. DMS should still handle the case when "nofail" is not set.
