### ISSUE TITLE
Preserve /var/log/zypper.log

### ISSUE THREAD

**Issue by schaefi** [SUSE/suse-migration-services#168]
Even if called with the --root option zypper logs to /var/log on the migration live system. These log information should be part of the host for better debugging

**Comment by ikapelyukhin** [comment]
In the ideal troubleshooting scenario the issue should be reported as a bug with a supportconfig tarball attached.

So ideally distro migration system should put those logs somewhere where public cloud supportconfig plugin can pick them up. Or there should be a new supportconfig plugin that comes with distro migration system that would ensure that those logs are shipped.
