### ISSUE TITLE
Complex filesystem layout does not get detected and configured correct.

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/suse-migration-services#189]
We have LVM with EXT4 and /usr on separate LVM partition. In this case there are multiple problems:

1) insmod ext4 in grub.cfg
-> there is no ext4 module and we have to use ext2 module (fixed by manually adjusting grub.cfg and replacing ext4 with ext2)

![grafik](https://user-images.githubusercontent.com/13362573/109503081-19b86800-7a9a-11eb-85cf-ed53001cda7b.png)

2) no lvm module loaded (fixed 1 manually)
(manually fixed by adding insmod lvm)

![grafik](https://user-images.githubusercontent.com/13362573/109503106-2210a300-7a9a-11eb-82e3-08292ec4de1d.png)

3) even with the manual fix for the above two - the service does not start:

![grafik](https://user-images.githubusercontent.com/13362573/109503139-2b9a0b00-7a9a-11eb-98bd-24d03b60d1c5.png)

so we copied the iso to / and rebooted

4)

![grafik](https://user-images.githubusercontent.com/13362573/109503373-79167800-7a9a-11eb-8303-89412d335c31.png)

5) this is the disk layout we have:

![grafik](https://user-images.githubusercontent.com/13362573/109503230-4d938d80-7a9a-11eb-8a6b-6d6541380c8a.png)

![grafik](https://user-images.githubusercontent.com/13362573/109503273-584e2280-7a9a-11eb-9d34-fd6bf488de38.png)

**Comment by rjschwei** [comment]
covered in bsc#1180712

The ext4 issue is already fixed commit 328fceb8d3405f

**Comment by schaefi** [comment]
The LVM issue is now also fixed with #192 and #195
