### ISSUE TITLE
DMS fails due to multiple mount attempt of special filesystem

### ISSUE THREAD

**Issue by rfparedes** [SUSE/suse-migration-services#191]
This issue has come up numerous types with customers that include special filesystems explicitly in their /etc/fstab.  For instance, a customer fstab may look like:

```
/dev/hda1       /       ext4    defaults 1 1
tmpfs   /run    tmpfs   noauto 0 0
sysfs   /sys    sysfs   noauto 0 0
debugfs /sys/kernel/debug       debugfs noauto 0 0
proc    /proc   proc    defaults 0 0
devpts  /dev/pts        devpts  mode=0620,gid=5 0 0
```

During the mount_system, the DMS will itself mount devtmpfs, proc, sysfs, etc. But since the customer fstab includes the special filesystems already, the mount_system will fail and as a result, the migration aborts.

Proposing changing the fstab.py to not only ignore swap but all special filesystems (or at least the special filesystems the DMS explicitly mounts),  as it is unknown what the user may have in their /etc/fstab.

Instead of:
`if fstype != 'swap':`

Propose:
`if fstype not in ['swap','tmpfs','sysfs','debugfs','proc','devtmpfs','dev','devpts']:`

**Comment by schaefi** [comment]
There will be a PR soon
