### ISSUE TITLE
Custom MACAddressPolicy not respected in live migration system

### ISSUE THREAD

**Issue by schaefi** [SUSE/suse-migration-services#200]
If a system configures a MACAddressPolicy which is not standard like it's the case for the Azure LI/VLI images as an example, it's hard for the live migration system to boot with the same policy settings.

The MACAddressPolicy directly impacts the NIC interface names and therefore is crucial for setting up the network in the live migration in the same way as it would be done on boot of the system to upgrade

MACAddressPolicy can be influenced by e.g

* usr/lib/systemd/network/80-azure-li-net.link

```
[Link]
NamePolicy=mac
MACAddressPolicy=persistent
[Match]
OriginalName=*
```

A generic solution in the DMS therefore should be able to read the current MACAddressPolicy on the host and pass along this as a kernel boot option to the live migration system. I'm not sure if this is possible or if it's required to configure this in the live migration system. If a configuration is needed there must also be a way to re-init systemd such that the new setting becomes effective before the network service gets started

Overall not an easy problem to solve and needs some investigations beforehand

**Comment by schaefi** [comment]
This issue can be solved via the container based upgrade workflow. In case a customer has special needs that are hard to solve through the standard offline process like in this case, I propose to switch to the container process as stated here: #292

**Comment by rjschwei** [comment]
This is something we could stick into the pre-checks and warn the user about.
