### ISSUE TITLE
HPC image migration fails with error

### ISSUE THREAD

**Issue by jeremy-moffitt** [SUSE/suse-migration-services#238]
The DMS documentation needs to be updated to indicate that SLES12 HPC images cannot be migrated

see the following note from Robert:

```
In SLE 12 HPC was a module of SLES which was also available for
SLES4SAP. In SLE 15 HPC became it's own product. While there is still a
HPC module that module is now part of the HPC product and no longer part
of the SLES or SLES4SAP products, which is why before a migration of
SLES or SLES4SAP the HPC module needs to be removed from PAYG instances
or the migration will fail. And BYOS instances if the HPC module is set up.
```

Attempting to migrate an HPC instance results in the following error:

```
Can't get available migrations from server: SUSE::Connect::ApiError: Internal Server Error
'/usr/lib/zypper/commands/zypper-migration' exited with status 1
EXEC: Failed with stderr: (no output on stderr), stdout: (no output on stdout)
migrate service failed with bash: stderr: (no output on stderr), stdout: (no output on stdout)
```

**Comment by schaefi** [comment]
For the selected set of repositories there is no migration path available. It's strange that it ended up as an internal server error though. The right people to connect are the ones hosting the contacted repository server (SCC ?)

There is little you can do from the perspective of the migration other than re-checking if the repository setup on the host to migrate is eligible to be updated through the used repository server
