### ISSUE TITLE
Add backup recommendation

### ISSUE THREAD

**Issue by djrsatx** [SUSE/suse-migration-services#252]
Please add a statement for a backup recommendation in section "2. Upgrade Prerequisites".

**Comment by KeithMnemonic** [comment]
Backup recommendations are provided in the SLES documentation.  https://documentation.suse.com/sles/15-SP1/single-html/SLES-upgrade/index.html#cha-update-preparation . DMS just provides a method to launch the migration for instances running in one of the support public cloud platforms.
