### ISSUE TITLE
Output of /usr/bin/suse-migration-pre-checks

### ISSUE THREAD

**Issue by samuelfusato** [SUSE/suse-migration-services#253]
Dear Team,

I would like to know if it's possible and feasible to add the output of `/usr/bin/suse-migration-pre-checks` as an example in the documentation in [this part](https://documentation.suse.com/suse-distribution-migration-system/15/single-html/distribution-migration-system/#id-upgrade-pre-checks). For example:

```
sles12-sp5:/etc/zypp # /usr/bin/suse-migration-pre-checks -f
Running suse-migration-pre-checks with options: fix: True
Device path 10.123.45.678:/usrsaptrans/EWM not found and skipped
Device path 10.123.45.678:/symbackup/ewx not found and skipped
Calling: ['blkid', '-s', 'TYPE', '-o', 'value', '/dev/disk/by-uuid/56574c71-9967-4f8b-b8ff-b2b914de277f']
Calling: ['blkid', '-s', 'TYPE', '-o', 'value', '/dev/disk/by-uuid/dc679d7a-bd33-4f70-8221-878911791f12']
Calling: ['blkid', '-s', 'TYPE', '-o', 'value', '/dev/disk/by-uuid/CA25-C086']
Calling: ['blkid', '-s', 'TYPE', '-o', 'value', '/dev/sap/mnt']
Calling: ['blkid', '-s', 'TYPE', '-o', 'value', '/dev/sap/usrsap']
The config option 'multiversion' in /etc/zypp/zypp.conf includes the keyword 'kernel.' The current value is set as
'multiversion = provides:multiversion(kernel)'.
Checking the config option 'multiversion.kernels' to see if multiple kernels are also enabled
Calling: ['rpm', '-qa', 'kernel-default']
```

The above output is supposed to be interpreted as "it passed, no issues found and you are ready to migrate"?

Thank you.

**Comment by KeithMnemonic** [comment]
We can update the documentation. I will work on a PR in the near future to add this.

**Comment by KeithMnemonic** [comment]
@samuelfusato I am working on this now. Is this sufficient?

![image](https://user-images.githubusercontent.com/9559808/206755264-fbc47c02-95ab-4e82-b781-80140d434c79.png)
