### ISSUE TITLE
Automatically retry after an error during the upgrade

### ISSUE THREAD

**Issue by casierjean** [SUSE/suse-migration-services#259]
Hello Team,

When performing the upgrade, we had some issues happened during the packages upgrade like this one :

![image](https://user-images.githubusercontent.com/96172232/227156977-e38bd2bf-9358-4c22-a782-b78b027ce4a9.png)

Do you know if there is a possibility to choose to automaticaaly retry instead of aborting the upgrade ?

Thanks !

**Comment by KeithMnemonic** [comment]
The upgrade is being performed by the `zypper-migration` plugin/command.  This would need to be something that command would offer as an option.  I do not think that currently exists though unfortunately.  You could post a question here https://github.com/SUSE/zypper-migration  and see what response you get .   I wish I had a better answer.  I do not think it would make sense for suse-migration-services to "blindly" call zypper migration again (#n retries) if it detected a failure as that could lead to a very corrupted system.   Ideally a retry mechanism built into zypper/zypper-migration could evaluate the error and determine if a retry makes sense.

**Comment by casierjean** [comment]
Yes i'm sorry you are right.

Thanks for your answer and sorry to have disturbed you
