### ISSUE TITLE
Workaround for LVM support

### ISSUE THREAD

**Issue by doccaz** [SUSE/suse-migration-services#277]
Recently while testing DMS to help a customer migrate its VMs,  I noticed that most of their VMs use a complex layout with LVM, and thus DMS would fail (as described in the documentation). 

The issue is that GRUB cannot find the ISO after rebooting, as their /usr lives on a separate LV, and the logic in 99_migration would evaluate the final path as "/share/migration-image/<ISO name>", as it assumes /usr is under the root partition.

I managed to get it working with a workaround. Right before rebooting, run these commands:
```
# mkdir /share
# cp -av /usr/share/migration-image /share/

# sed -i '/insmod %s/a printf \"    insmod lvm\\n\"' /etc/grub.d/99_migration 
# grub2-mkconfig -o /boot/grub2/grub.cfg
``` 

So, with these I'm: 
* copying the migration-image directory to the root partition, so the path to the ISO as-is will evaluate to a valid ISO
* adding the "lvm" GRUB module so it can find the LVM root partition 

This will, of course, occupy an extra 400MB or so (the migration ISO image size) on the root partition, but this space can be reclaimed after the migration.

I could have written the proper GRUB logic to find the /usr partition, but I think this could vary quite a lot. Maybe we could leave the ISO on a different directory at the root partition, like I did with the workaround? Something like "/migration-image" is very unlikely to exist as a separate LV on any setup.

**Comment by schaefi** [comment]
I like the idea to move the space to store the live migration image at a place which is unlikely to be used in a complex storage setup. The proposed location directly below `/` is an option however I believe our package people will decline the submission because not FHS compliant.

On the other I think we have to use a non FHS compliant directory because any FHS compliant path is subject to a more complex storage layout and can be a snapshot a volume a tmpfs or anything like that.

**Comment by schaefi** [comment]
JFI: #292 also solves this issue and many more... but is unsupported by SUSE

**Comment by doccaz** [comment]
> I like the idea to move the space to store the live migration image at a place which is unlikely to be used in a complex storage setup. The proposed location directly below `/` is an option however I believe our package people will decline the submission because not FHS compliant.
> 
> On the other I think we have to use a non FHS compliant directory because any FHS compliant path is subject to a more complex storage layout and can be a snapshot a volume a tmpfs or anything like that.

I guess an exception to this rule could be added. Do we really need to be 100% FHS-compliant for a package that will be erased right after its intended purpose on the system?

**Comment by schaefi** [comment]
>I guess an exception to this rule could be added. Do we really need to be 100% FHS-compliant for a package that will be erased right after its intended purpose on the system?

probably not. I'll create a PR and we can discuss from there

**Comment by schaefi** [comment]
@doccaz I submitted a PR which should follow your idea. Would be great if you also can take a look #303 

Also you find the complete DMS stack build for testing here:

* https://build.opensuse.org/project/show/home:marcus.schaefer:dms

Thanks much
