### ISSUE TITLE
SUSE migration services pre-check for non-activated services with lingering module packages

### ISSUE THREAD

**Issue by thimslugga** [SUSE/suse-migration-services#290]
The SUSE migration services pre-checks should make sure that "non-activated" services are actually not activated. I've seen where the customer has switched from SUSE Manager back to directly communicating with SCC and `updates.suse.com` and from SUSEConnect perspective the products were not "activated". However the customer had the related module packages still installed on the host. During the dist migration it was failing due to refreshing of the "non-activated" services.

**Comment by schaefi** [comment]
I guess your workflow is based on the zypper migration plugin. So the DMS calls this in the following way 

```
[
                    'zypper', 'migration',
                    verbose_migration,
                    '--non-interactive',
                    '--gpg-auto-import-keys',
                    '--no-selfupdate',
                    '--auto-agree-with-licenses',
                    '--allow-vendor-change',
                    '--strict-errors-dist-migration',
                    '--replacefiles',
                    '--product', migration_config.get_migration_product(),
                    '--root', root_path,
                    '&>>', Defaults.get_migration_log_file()
                ]
```

The implementation of the migration plugin determines how the installed product and services are used. As far as I can see we do not actively refresh or enable zypper services.

From that perspective do you think this is still something the DMS has to solve ? If yes can you share a log file of a failed attempt ? Thanks

**Comment by rjschwei** [comment]
This sounds like it is related to "left over" release packages, meaning something that has no migration target is still on the system. There are no APIs that allows us to collect all the "products" installed and as "is there a migration target for this". As such I don't see how we can do any better client side, i.e. in DMS than to try the migration and then when it fails report accordingly.

**Comment by schaefi** [comment]
I agree
