### ISSUE TITLE
Report migration error in /etc/issue

### ISSUE THREAD

**Issue by schaefi** [SUSE/suse-migration-services#47]
In case of an error the migration system should write a file ```/system-root/etc/issue" which contains something like:

* Migration has failed, for further details see /var/log/zypper_migrate.log

This will give users a direct pointer to the state of the migration when they log in back to the system.
In case of success no further information is needed imho

**Comment by rjschwei** [comment]
Agreed, while we do this we should rename the log file. IMHO the name "zypper_migrate.log" implies that this is related to a zypper operation. While zypper is part of the process it is far from the only component in the migration system. I suggest "distro_migration.log" as name for the log file.
