### ISSUE TITLE
Reboot of the migration system

### ISSUE THREAD

**Issue by schaefi** [SUSE/suse-migration-services#48]
Currently the migration system reboots only if everything went fine

In case of an error in any of the services in the pipeline, the reboot service is not called and we leave the user in the migration system.

* I think we should reboot the system in any case and report trouble as written in #47 
* I think we should allow a way to let us debug the process by passing an option to avoid reboot. It's not clear how that option should reach the migration system. So this is still an open discussion point

**Comment by rjschwei** [comment]
The argument for leaving the system in the migration state is for immediate access to debug the issue, i.e. a user has access to the migration system, can potentially make necessary changes and continue the process.

The argument against leaving the system in the "migration state" is that the system is more or less useless. If we have a successful roll back and reboot the system can be used in it's original state and be re-introduced into production mode basically immediately while in parallel investigating the root cause of the failure of the migration.

IMHO the later is more practical and has a distinct advantage over the first approach. Thus I agee with the idea that we should reboot the system even if migration fails.

As far as debugging is concerned, i.e. avoid the reboot I propose the user simply puts "/etc/system_migration_debug" into place. Before reboot upon failed migration we check the presence of the file. If it's there we remain in the migration system otherwise we remove the file and reboot.

**Comment by schaefi** [comment]
> As far as debugging is concerned, i.e. avoid the reboot I propose the user simply puts
> "/etc/system_migration_debug" into place. Before reboot upon failed migration we check the
> presence of the file. If it's there we remain in the migration system otherwise we remove the file and 
> reboot.

This is a good idea :+1:

**Comment by schaefi** [comment]
> As far as debugging is concerned, i.e. avoid the reboot I propose the user simply puts
> "/etc/system_migration_debug" into place.

I think it would be even better to put a let's name it config file for migration into place. e.g ```/etc/system_migration.yaml```

and allow content like this

```yaml
debug:
    enable: true
```

It will allow us to control how the migration should work more comfortable

> into place

There was imho a misunderstanding of where the file should live. I think it should be created on the system which we want to migrate. Such that we can control behavior __before__ reboot. The current implementation in #51 is searching the file inside of the migration live system. This would imply the config file is part of the live migration system and would need to be added there at build time of the image. This is imho the wrong place and also its contents are not controllable by the user running the migration, it would only be under control by the people building the live migration image

**Comment by rjschwei** [comment]
Hmm, I am not convinced that we want to put a config file in place. Logic dictates that if we have a config file people will ask for

`migration:
    target: sles-15-sp1`

we are opening the door to a whole can of worms that then require well documented rules such as "you target may be X Y Z but not A B C"

Also having a config file requires more documentation than "to debug the mygration process run 'touch "/etc/system_migration_debug" and re-run the migration.

**Comment by jesusbv** [comment]
I like the flexibility that the config files offers, however the only purpose of the file is to indicate not reboot to be able to debug inside the failed migration system. Thus, imo, a simple empty file seems to fill that need. If we want to control other behavior than just the reboot debugging or others needs will more likely appear then it should be a config file.

**Comment by schaefi** [comment]
>If we want to control other behavior than just the reboot debugging or others needs will more likely
> appear then it should be a config file.

I'm sure this will happen in the future once the system is in place. I'm thinking of further access control, thinking of configuring strictness in case of zypper error codes. e.g should 104 be an error or not. thinking of console control.... anything to control the behavior of the migration live system would be useful to end up there because the customer will have no opportunity to rebuild the migration live image.

In the beginning you are right the config file only controls the debug flag. So be it and reading yaml is a one line in python returning you a dictionary. If we go with one empty file as indicator and realize we need more we can't delete the file anymore because this is a "public interface". I would go with a conf file and have full flexibility to do whatever we want. If it means the debug flag is the only thing we control, ok it wouldn't hurt :)

**Comment by rjschwei** [comment]
But an empty file can easily be converted into a full config file. Let's assume we name this:

`/etc/sle-migration-service`

then in pseudo code today we would have:

`
if os.path.exists(os.sep.join([root_path, '/etc/sle-migration-service'])):
  no_migration_system_reboot = True
`

and in the future if we do have more config options we can easily turn this into

`
if os.path.exists(os.sep.join([root_path, '/etc/sle-migration-service'])):
    config = open(os.sep.join([root_path, '/etc/sle-migration-service']), 'r').read()
    if config:
        cfg = yaml.loads(config)
    else:
        no_migration_system_reboot = True
`
So the semantic of "empty file means migration system debug" remains the same and is fully compatible and we have a migration path from en empty file to a config if we need it.
