### ISSUE TITLE
Migration of Systems with small boot partition

### ISSUE THREAD

**Issue by schaefi** [SUSE/suse-migration-services#54]
I was testing the migration process using a SLES12 SP4 instance in AWS. This image is designed by us using an XFS root partition and an extra boot partition of 300MB size. Our live migration image gets installed intentionally below /boot because of the reasons explained here #45 

Now the 300MB are not big enough to install the SLES15-Migration package:

```
zypper in SLES15-Migration
Refreshing service 'SMT-http_smt-ec2_susecloud_net'.
Refreshing service 'cloud_update'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following NEW package is going to be installed:
  SLES15-Migration

The following package has no support information from it's vendor:
  SLES15-Migration

1 new package to install.
Overall download size: 0 B. Already cached: 189.1 MiB. After the operation,
additional 229.0 MiB will be used.
Continue? [y/n/...? shows all options] (y): y
In cache SLES15-Migration-1.15.0-26.x86_64.rpm
                                           (1/1), 189.1 MiB (229.0 MiB unpacked)
Checking for file conflicts: .............................................[done]
(1/1) Installing: SLES15-Migration-1.15.0-26.x86_64 .....................[error]
Installation of SLES15-Migration-1.15.0-26.x86_64 failed:
Error: Subprocess failed. Error: RPM failed: warning: /var/cache/zypp/packages/suse-migration/SLES15-Migration-1.15.0-26.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID 8a7c64f9: NOKEY
	installing package SLES15-Migration-1.15.0-26.x86_64 needs 15MB on the /boot filesystem
```

Older images are designed differently such that the size limit on /boot is of no relevance.
But now as SP4 is out the 300MB fixed boot partition is a big problem

**Comment by schaefi** [comment]
The live migration system is already made small, I took  a short look and the investment to make it smaller would be relatively big and ist not a stable solution too

**Comment by schaefi** [comment]
Thought more on this. So even if we make the activation script smart enough to detect the rootfs location in grub speach e.g (hd0,2) it would not work because the extra boot partition has it's purpose because grub cannot directly read the rootfs. XFS in your case cannot be read directly by grub which is why there is a boot partition. This means the image must be on a grub supported fs such that grub's loopback feature can work.

This also means if the boot partition is not big enough >= 500M we are screwed

The good news is the customer gets this feedback at install time and nothing serious to his system happens but the migration system will not work on such systems.

I have no good solution to this problem

**Comment by jesusbv** [comment]
It happened to me this morning testing it in GCE, asking 14MB for /boot.

**Comment by schaefi** [comment]
> we shall stop its development ?

You are giving up too fast :)

So I investigated further and just saw grub natively supports reading xfs, btrfs and extX. So there is no reason to have a extra boot partition.

@rjschwei I wonder why we create the images using an extra bootpart of 300MB. It looks a bit like we did that because it's kiwi's default. But there is actually no reason to do that. So we could, and imho really should, set the following in the image descriptions:

```
bootpartition="false"
```

**Comment by schaefi** [comment]
As SP4 is already out and public customers can use it and we have to find a solution here. However as we have the support in grub for the fs we can make the activation code smarter. Actually I don't like this because we have to invent intelligence that shouldn't be needed but it is at least possible

**Comment by schaefi** [comment]
I will look into that and come up with a patch

**Comment by schaefi** [comment]
we have to revert the move of the image to /boot and store it into the system

**Comment by jesusbv** [comment]
> > we shall stop its development ?
> 
> You are giving up too fast :)
Sorry that came out wrong, not giving up at all. Just curious about if there is anything we could do or not.

**Comment by rjschwei** [comment]
> > we shall stop its development ?
> 
> You are giving up too fast :)
> 
> So I investigated further and just saw grub natively supports reading xfs, btrfs and extX. So there is no reason to have a extra boot partition.
> 
> @rjschwei I wonder why we create the images using an extra bootpart of 300MB. It looks a bit like we did that because it's kiwi's default. But there is actually no reason to do that. So we could, and imho really should, set the following in the image descriptions:
> 
> ```
> bootpartition="false"
> ```

@schaefi no problem with setting 

```
bootpartition="false"
```

Note that unlike the Azure images where we were specifically asked for creating a /boot partition the AWS and GCE images use the default kiwi behavior and do not specify a specific path.

In any event these images are published and we have to handle the small /boot partition kiwi creates.
