### ISSUE TITLE
Verify handling of file conflicts

### ISSUE THREAD

**Issue by rjschwei** [SUSE/suse-migration-services#58]
How do we handle a packaging bug where file conflicts exists?

Does zypper migration handle this "properly" for us? zypper itself has a "--replacefiles" option, does the migration plugin have a similar command line option? If yes, we should use it.

**Comment by jesusbv** [comment]
Yes, the option exists. I will add it.

**Comment by jesusbv** [comment]
I was testing the ```--replacefiles``` option yesterday and I couldnt not reproduce any file conflict to check it works. I have found package conflicts, because I chose specific images that are more likely to happen (beta or rc images). For example:
```
N problems:
Problem: problem with installed package xxxxx
...

Problem: problem with installed package xxxxxxxx.noarch
   Solution 1: xxxxxxxx.noarch (with vendor change)
    solution
   Solution 2: keep obsolete xxxxxxxx.noarch

   Choose from above solutions by number or skip, retry or cancel [1/2/s/r/c] (c): c
```

So the migration fails and rolls back successfully.
I understand you do not mean this type of conflicts.

**Comment by rjschwei** [comment]
The conflict only arises when there are packaging bugs. You can try and test on a SLES 12 SP1 For SAP instance. It has file conflicts for release packages. I realize we do not want to support a migration that starts at SP1, but it might work for test purposes.

We do know that packaging bugs like this slip through every now and then and thus we need the option even if we cannot test it.

**Comment by schaefi** [comment]
> The conflict only arises when there are packaging bugs.

or someone tries to upgrade from a non-released version of suse. I had a brief conversation with Jesus on the phone and he told me when he tested the migration on GCE there were image available flagged as "Beta-1", or "RC-3" or something. Those state of a distribution could cause the conflict states. I would say our upgrade process does not support this. Also the official documented way DVD+YaST also does not support this. I wondered how those image builds made its way to GCE but probably this was on a non public project

>We do know that packaging bugs like this slip through every now and then and thus we need the option >even if we cannot test it.

yes file conflicts are probably inevitable here and there. It does not hurt to add this option

@jesusbv would be great to get that done. There is a chance to let a customer with SAP running to do some further testing for us and I think it would be good to have this fixed if we hand over stuff there.

Overall having some customers testing this is very valuable. The more we can get, the better. I mean before we make something official
