### ISSUE TITLE
Support new cloud-regionsrv-client

### ISSUE THREAD

**Issue by ikapelyukhin** [SUSE/suse-migration-services#69]
New `cloud-regionsrv-client` service plugin outputs repositories with `plugin:/susecloud` URLs, which breaks migration, as the live migration system is missing URL resolver plugin.

In the future, the update server will also require instance metadata to allow access to the repositories, so the live system also needs to be able to collect it.

Potential solutions that we've briefly discussed with @schaefi and @jesusbv:

1. Copy/mount zypper plugins and metadata gathering utils from the host system
2. Bake `cloud-regionsrv-client-plugin-$csp` into the live system image (this, however, makes it CSP-specific).

**Comment by ikapelyukhin** [comment]
@rjschwei ping for interest.

**Comment by schaefi** [comment]
I think I would go with the first suggestion because I don't want to create csp specific migration images. That would significantly increase the maintenance work and will make it harder for customers to choose the right one.

As the live migration system comes with the mandatory zypper-migration plugin pre-installed the mount method will not be the right choice. So we can copy/rsync the plugin install from the system to become migrated onto the live migration system. @ikapelyukhin could you provide the details which plugin paths we need to take into account: ```/usr/lib/zypp/plugins/?``` I'm sorry I can't remember from the discussion we had which one was relevant. Thanks

Other than that does the plugin code require python modules or other packages ? If we just copy the code we would miss dependencies if there are any. @ikapelyukhin if you can share the list of dependency regarding the plugin code I can add them to the migration image such that we can be sure the plugin will work after we copied it.

Thanks

**Comment by ikapelyukhin** [comment]
@schaefi 

1. Plugins: yep, `/usr/lib/zypp/plugins/`, more specifically -- `/usr/lib/zypp/plugins/urlresolver/`. 
2. Dependencies: I'd suggest that you check [cloud-regionsrv-client package dependencies](https://github.com/SUSE-Enceladus/cloud-regionsrv-client/blob/master/cloud-regionsrv-client.spec#L28-L40) and maybe the source. The plugins also use Python modules from `%{python3_sitelib}/cloudregister/` that come with the package.

**Comment by ikapelyukhin** [comment]
@schaefi Also note that the plugin will need to call the binary defined by `dataProvider` option in `[instance]` section of `/etc/regionserverclnt.cfg`. Values are defined by `regionServiceClientConfig$CSP` packages.

**Comment by schaefi** [comment]
Hmm, so there is a lot more than just copying some plugin code. Especially the fact that the cloud-regionsrv-client package itself provides python modules scares me. So this will end up in a hack solution and any change done to the plugin code will most probably break the migration.

* Wouldn't it be possible to install all packages providing the regionsrv-client-* packages to the live migration image
* Add a service to the migration code that just copies the configuration for the client from the system to migrate into the live migration image ?

The original idea to copy plugin code doesn't sound practical to me after we got the details

Thoughts ?

**Comment by ikapelyukhin** [comment]
@schaefi well, yes, considering how deep this rabbit hole is, it might be more practical to just build CSP-specific live images and include all the dependencies via package requires.

**Comment by schaefi** [comment]
So how about the following workflow:

1. Update live migration image description and add

    ```xml
    <package name="cloud-regionsrv-client"/>
    <package name="cloud-regionsrv-client-generic-config"/>
    ```

    That should resolve all dependencies iirc

2. Update live migration image config.sh and and disable registration service

     ```
     suseRemoveService guestregister
     ```

3. Write service code in the migration system to search and copy ```/etc/regionserverclnt.cfg``` and maybe more metadata files that are needed ?

**Comment by jesusbv** [comment]
That workflow seems good to me. It would be good as @schaefi commented to avoid live migration per CSP as much as possible.

**Comment by ikapelyukhin** [comment]
@schaefi You'd still be missing stuff that `regionServiceClientConfig$CSP` packages provide.

**Comment by ikapelyukhin** [comment]
@schaefi please look at IRC sometimes :D

**Comment by schaefi** [comment]
ok, thanks Ivan for the update on irc. So in addition to the above packages we also add

```xml
<package name="python3-gcemetadata"/>
<package name="python3-ec2metadata"/>
<paclage name="azuremetadata"/>
```

those are all metadata tools that do not conflict with each other. Once the plugin needs them they will be available. So the live migration image can still stay generic if all information which is cloud specific comes from ```/etc/regionserverclnt.cfg``` which we need to search on the system to become migrated

@ikapelyukhin @rjschwei time for objections :)

**Comment by rjschwei** [comment]
@schaefi 

Almost, there is an additional wrinkle, sorry. After running instances upgrade to the latest regionsrv-client package /etc/zypp/services.d will be emptied and a properly named symlink in /usr/lib/zypp/services will be created. That symlink points to code provided by the cloud-regionsrv-client package. So in addition to the packages that need to be added per earlier comments the migration service still needs to mount "/usr/lib/zypp/plugins" into the migration system. Only needed if regionserverclnt.cfg exists.

That should catch everything.

**Comment by schaefi** [comment]
> the migration service still needs to mount "/usr/lib/zypp/plugins" into the migration system.

I checked if we can do that with regards to the zypper-migration-plugin. So the zypper migration plugin
just installs a command:

```
rpm -qpl /home/ms/.cache/zypp/packages/download.opensuse.org-oss/noarch/zypper-migration-plugin-0.11.1520597355.bcf74ad-lp150.1.1.noarch.rpm
/usr/lib/zypper/commands
/usr/lib/zypper/commands/zypper-migration
/usr/share/man/man8/zypper-migration.8.gz
```

This means it should not contradict with /usr/lib/zypp/plugins. I'll update the image description and prepare a patch

**Comment by schaefi** [comment]
I've updated the package list and the config.sh service setup in the image description

**Comment by schaefi** [comment]
Just for reference:

```
----------------------------------------------------------------------------
r32 | sax2 | 2019-04-09 08:15:16 | 3b4aa502a4d264d516b18158dde86fe6 | 1.15.0 | 
```
