### ISSUE TITLE
Remove hard requirement on suse-migration-activation

### ISSUE THREAD

**Issue by tserong** [SUSE/suse-migration-services#74]
Currently, the SLES15-Migration package requires suse-migration-activation, which adds the relevant grub config to reboot into the migration system. So, install the migration package, reboot, migrate, and you're done. This is ideal for single systems, but doesn't work for cases such as Ceph clusters where there are multiple hosts that need to be upgraded in a particular sequence.

To handle this case, can we remove the requirement for the activation package in SLES15-Migration? This would mean documenting that an activation step is required before reboot. For the simple case, that would mean documenting that you have to install suse-migration-activation. In the case of a Ceph cluster that would involve invoking some DeepSea/salt task to trigger the activation, which would be covered separately in the SUSE Enterprise Storage docs.

**Comment by rjschwei** [comment]
@tserong Is the concern that a SES node would have to be re-booted after the migration packages are installed but before that particular node is supposed to be rebooted for the migration?

**Comment by tserong** [comment]
@rjschwei for SES, we want to orchestrate (or at least manage, if not completely automate) migration of all nodes in the cluster, in a particular order, and after performing certain checks for cluster health. This will be done by DeepSea/salt (possibly with some extra scripts), and definitely with some detailed documentation.

The concern is that once we make the SLES15-Migration package available in the relevant update channels, it's possible for a user to go install that package by hand (`zypper in SLES15-Migration` or whatever), then suddenly the system is configured to migrate on next reboot. If the user then goes and reboots that system, without understanding the upgrade sequence (let's pretend they ignored the documentation), they're probably going to break their cluster.

**Comment by rjschwei** [comment]
@tserong we had a discussion about the SES use case and how it would match with other uses, for example in the Public Cloud we want the "install one package and reboot" experience. However, the SES use case is certainly valid and would potentially apply to other clustered setups, my it be CaaSP or other clusters.

We will remove the existing `Requires:  suse-migration-activation` to cover use case. The Public CLoud use case will be covered by a meta package `cloud-migration`.

Thanks for bringing this up
