### ISSUE TITLE
Failure in zypper migration installs SLES 15 SP1 / SES 6 release RPMs

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/suse-migration-services#85]
I have just tried the current version of sle-migration-service with this process (no SCC/RMT/SMT registration):

1. delete all zypper repos 

```
zypper sd {0..99}
```

2. connect sles 15 sp1 + ses 6 repos

```
Repository priorities are without effect. All enabled repositories share the same priority.

# | Alias                                        | Name                                         | Enabled | GPG Check | Refresh | URI--+----------------------------------------------+----------------------------------------------+---------+-----------+---------+-----------------------------------------------------------------------------------------1 | SES6-POOL                                    | SES6-POOL                                    | Yes     | (r ) Yes  | Yes     | 
http://smt.suse/repo/SUSE/Products/Storage/6/x86_64/product/2 | SES6-UPDATES                                 
| SES6-UPDATES                                 | Yes     | (r ) Yes  | Yes     | 
http://smt.suse/repo/SUSE/Updates/Storage/6/x86_64/update/3 | SLE-Module-Basesystem15-SP1-Pool             
| SLE-Module-Basesystem15-SP1-Pool             | Yes     | (r ) Yes  | Yes     | 
http://smt.suse/repo/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product/4 | SLE-Module-
Basesystem15-SP1-Updates          | SLE-Module-Basesystem15-SP1-Updates          | Yes     | (r ) Yes  | 
Yes     | http://smt.suse/repo/SUSE/Updates/SLE-Module-Basesystem/15-SP1/x86_64/update/5 | SLE-
Module-Server-Applications15-SP1-Pool    | SLE-Module-Server-Applications15-SP1-Pool    | Yes     | (r ) 
Yes  | Yes     | http://smt.suse/repo/SUSE/Products/SLE-Module-Server-Applications/15-
SP1/x86_64/product/6 | SLE-Module-Server-Applications15-SP1-Updates | SLE-Module-Server-
Applications15-SP1-Updates | Yes     | (r ) Yes  | Yes     | http://smt.suse/repo/SUSE/Updates/SLE-
Module-Server-Applications/15-SP1/x86_64/update/7 | SLE-Product-SLES15-SP1-Pool                  | 
SLE-Product-SLES15-SP1-Pool                  | Yes     | (r ) Yes  | Yes     | 
http://smt.suse/repo/SUSE/Products/SLE-Product-SLES/15-SP1/x86_64/product/8 | SLE-Product-
SLES15-SP1-Updates               | SLE-Product-SLES15-SP1-Updates               | Yes     | (r ) Yes  | Yes     
| http://smt.suse/repo/SUSE/Updates/SLE-Product-SLES/15-SP1/x86_64/update/

3. zypper in ~/ses6/suse-migration-sle15-activation-1.2.0-6.6.3.noarch.rpm ~/ses6/SLES15-Migration-
1.15.0-6.x86_64.rpm
```

4. touch /etc/sle-migration-service

5. reboot

-> the zypper migration failed as expected (I know I need the dup feature instead of migrate as I do not have SCC, SMT or RMT)

BUT - somehow the zypper process installed these release RPMs:

```
ses-5-1:~ # rpm -qa --last|headsles-release-15.1-62.4.x86_64                 Mon May 20 13:55:36 2019ses-release-6-61.1.x86_64                     Mon May 20 13:55:35 2019ceph-osd-12.2.12+git.1555518691.67074fa839-2.33.1.x86_64 Fri May 10 20:45:20 2019ceph-12.2.12+git.1555518691.67074fa839-2.33.1.x86_64 Fri May 10 20:45:20 2019
```

I would have expected that in case there is a problem with zypper migrate - nothing is installed and just the migration RPMs are removed.. but for some reason the release RPMs got installed..

Do you have any idea why?

**Comment by Martin-Weiss** [comment]
[distro_migration.log](https://github.com/SUSE/suse-migration-services/files/3201080/distro_migration.log)
[zypper.zip](https://github.com/SUSE/suse-migration-services/files/3201082/zypper.zip)

**Comment by Martin-Weiss** [comment]
Documenting first feedback:

Looked at the logs you provided. On a first look I don't see an explicit
install of the release packages. I guess the following.

1. The zypper migration plugin sends a request to SCC asking for the
   upgrade path. That failed with: "Can't get available migrations from server"
   and is expected. But all repos for SLE15 has been built in and the
   product was already set to SLE15. We have to do this for the migration
   to work. Also see product_setup.py

2. Now the rollback kicks in, which first should recreate the former
   product setup (product_setup.py has created a backup) and then restore
   the repos. I guess during that rollback operation there might be
   the install of the sle15 release.

All this is a wild guess. There is for sure no code in the
suse-migration-services that installs those packages. So the trigger
is the migration plugin code.

**Comment by jesusbv** [comment]
Thanks to @Martin-Weiss for finding the [bug](https://bugzilla.suse.com/show_bug.cgi?id=1136737)
As it is an open bug and it is not this tool's responsibility, I will close this and keep an eye on the bug evolution.
