### ISSUE TITLE
Inherit ssh host key to live migration system

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/suse-migration-services#86]
When accessing the Live system via SSH we always get a warning that the SSH key of the server changed which normally can indicate a man-in-the-middle attack.
Would it be possible to inject the SSH keys of the running server into the Live system?

(not sure if the current behavior is at will)

**Comment by schaefi** [comment]
You mean the ssh host key. Yes this is a good point we could fetch those. The live image by default has no host key and sshd creates one at boot time. This causes the warning message.

**Comment by Martin-Weiss** [comment]
> You mean the ssh host key. 

Yes - exactly.

> Yes this is a good point we could fetch those. The live image by default has no host key and sshd creates one at boot time. This causes the warning message.

I am just not sure if we want people to know that they SSH into the Live system instead of the real system by choosing a different ssh host key. 

However - as we have just the user "migration" this should not be a problem and I would prefer to have the same key..

**Comment by rjschwei** [comment]
I think we should import the host keys from the system we are migrating to avoid the issue with the ssh warning and provoking security investigations.

Yes, having the specific user should be a hint, also we should probably set a motd in the live system.
