### ISSUE TITLE
Add an insecure feature for console login with username and password

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/suse-migration-services#87]
In case there are problems with the the network setup we might need local console login with the user migration or root using a password. It would be great if we could get an option that allows to specify such an insecure setting for the purpose of debugging i.e. in case there are network issues and ssh might not be possible or in case there are firewalls / ssh might be required on a different port etc.

**Comment by schaefi** [comment]
It implies you are having physical access to the machine, correct ?

**Comment by Martin-Weiss** [comment]
> 
> 
> It implies you are having physical access to the machine, correct ?

Yes - we expect that in VM environments we can get console access and on real hardware we have IPMI access.

**Comment by rjschwei** [comment]
Could also be a configuration option

```
root-password: 12345678
```

when set we can make the appropriate adjustments to the system. But yes this obviously opens a giant hole and maybe that's not really a good idea.

**Comment by schaefi** [comment]
I have another idea regarding this setting. So for the public cloud we really don't want to open that gate and we also don't want to have this configurable by the user.

For the SES use case we are in a private data center with possible access by humans. So the request makes sense there. I suggest that you take the image as we build it into your space and modify the following parts of the kiwi XML setup

* config.kiwi

```xml
<users>
        <user password="$1$wYJUgpM5$RXMMeASDc035eX.NbYWFl0" home="/root" name="root" groups="root"/>
        <user password="$1$wYJUgpM5$RXMMeASDc035eX.NbYWFl0" home="/home/migration" name="migration" groups="users"/>
</users>
```

modify the password hash with a passwd compatible hash that expresses the password you know

* config.sh

Delete the following lines:

```
# Remove the password for root and migration user
# Note the string matches the password set in the config file
sed -i 's/$1$wYJUgpM5$RXMMeASDc035eX.NbYWFl0/*/' /etc/shadow
```

We do this to make sure nobody can login with a password on the console. If you delete
the sed expression users can login with the password you have setup in the passwd hash

Last but not least if you even want password based access over the network go in and also
delete the following lines

```
# Disable password based login via ssh
sed -i 's/#ChallengeResponseAuthentication yes/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' \
    /etc/ssh/sshd_config
```

For creating the passwd hashes I usually use the ```openssl``` command

That way you can go live with an image where you control the access options and it will
not conflict with the approach we have to use in the public cloud. If you branch off from
Devel:PubCloud:Stable:ImagesSLE124P/SLES12-SP4-SLES15-Migration you will also notice any change we do on other parts of the system

Would that make sense ?

**Comment by tserong** [comment]
For the SES case, I've hardcoded a password for console access *only* (i.e. not network/ssh) in the kiwi image, so I think this can be closed.
