### ISSUE TITLE
Issue a warning on unsupported migrations

### ISSUE THREAD

**Issue by rjschwei** [SUSE/suse-migration-services#92]
Based on the discussion in #81 it was decided that it is not this code's job to enforce SUSE support policy. I think in an effort to allow the user to make an educated decision it would be helpful to issue a warning if the user selects a migration product that is out of bounds.

This could happen during the activation package installation. Check for existence of the config file in %post and if the current distribution is < SLES 12 SP3 or the configured target is > SLES 15 SP1 issue a warning that will then be displayed when the package installation is complete.

**Comment by jesusbv** [comment]
The warning is in place and it has been tested.
