### ISSUE TITLE
What timezone is used on the live system

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/suse-migration-services#93]
Does the live system also map the timezone settings from the installed and to be upgraded system so that the logs of the upgrade match to the timestamps of the server? (i.e. zypper log, rpm -qa --last,....)

**Comment by schaefi** [comment]
No this is not done. The live system runs in UTC

**Comment by schaefi** [comment]
Uh, actually wrong. <timezone>Europe/Berlin</timezone> is set for the live system.

Do you see any issue here ?

**Comment by Martin-Weiss** [comment]
> 
> 
> Uh, actually wrong. Europe/Berlin is set for the live system.
> 
> Do you see any issue here ?

Yes - we have seen that the timestamps in zypper.log did not match to Europe/Berlin. 
So the assumption was that for some reason the timezone is not set correct.

**Comment by schaefi** [comment]
So you are looking at /var/log/zypper.log ? where ? in /system-root/var/log/zypper.log or somewhere else ? What timezone is used for the entries you are referencing ?

Thanks

**Comment by Martin-Weiss** [comment]
> So you are looking at /var/log/zypper.log ? where ? in /system-root/var/log/zypper.log or somewhere else ?

Yes - in  /system-root/var/log/zypper.log (or in zypper.log on the upgraded system)

> What timezone is used for the entries you are referencing ?

It is also Europe/Berlin in my case.

I just tried to reproduce on a new installation but for some reason it seems I can not reproduce this at will..

Maybe the hardware clock was out of sync and during the reboot into the live system this was causing outdated time stamps in the log? An other guess would be UTC vs Local Time in the Bios - at the moment I am testing with UTC..

So now I have a more general question: do we clone the timezone and hwclock settings from the installed system also into the live system?

**Comment by schaefi** [comment]
I have changed the timezone for the live migration image to UTC. This should be imho ok and allows translation of time into any tzdata you prefer.

Regarding the hwclock I currently have no plans to inherit any ntp setup to the live migration system. For virtual systems like we see it in the public cloud we don't have this problem as the v-clock is in sync with the real time handled by the cloud service provider. For bare metal I agree with you if the bios time is out of sync and no network time protocol is in place the time during migration might be wrong.

If this will be a problem in the future that has to be fixed, let's discuss it in a new issue
